name: Generate Table of Contents for Documentation

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  generate-toc:
    name: Generate TOC for Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Checks out the repository so the workflow can access the files

      - name: Generate Table of Contents
        uses: actions/markdown-toc@v2 # Action to generate TOC
        with:
          file_glob: '**/*.md' # Process all Markdown files in the repository

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: Update TOC in Markdown files [skip ci]" || echo "No changes to commit"
          git push
